language: node_js
node_js:
  - 8.11.3
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
before install:
  - npm install -g npm@latest
  - npm install -g ionic
  - npm install -g cordova
install:
  - travis_wait
  - npm i
before_script:
  - npm prune
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - npm run test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $RAH_TOKEN
  keep-history: true
  on:
    branch: master

# Not to forget: local_dir: www