language: node_js
node_js:
 — “8.11.3”
branches:
 only:
 — master
before_script:
 — npm install -g ionic cordova
script:
 — ionic cordova build browser — prod
deploy:
 provider: pages
 skip-cleanup: true
 github-token: 9f5f764dbd10a9be32bc64cc941ddc253f992aeb
 keep-history: true
 on:
   branch: master
 local_dir: www