language: node_js
node_js:
  - 8.11.3
branches:
  only:
    - master
addons:
  chrome: stable
cache:
  directories:
    - node_modules
notifications:
  email: false
before install:
  - npm install -g npm@latest
  - npm install -g ionic
  - npm install -g cordova
install:
  - travis wait
  - npm i
before_script:
  - npm prune
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run lint
  - travis_wait npm run test
  - travis_wait npm run e2e
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local_dir: www