language: node_js
node_js:
 - 8.11.3
branches:
 only:
 - master
before install:
 - export CHROME_BIN=chromium-browser
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
before_script:
 - npm install -g ionic cordova
script:
 - npm run lint
 - npm run test
 - npm run e2e
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN
 keep-history: true
 on:
   branch: master
 local_dir: www